name: Create AZ Task
on:
  workflow_dispatch:
        inputs:
            title:
                description: 'Titulo del Task'
                required: true
                type: string
            description:
                description: 'Descripción del Task'
                required: true
                type: string
            areaPath:
                description: 'Area de trabajo del task'
                required: false
                type: string
                default: 'NTT Ingeniería de Plataformas\Versionador'
            activity:
                description: 'Actividad del task'
                required: false
                type: string
                default: 'Development'
            grupoResponsable:
                description: 'Grupo responsable de la actividad'
                required: false
                type: string
                default: 'Arquitectura'
jobs:
  create-task:
    runs-on: ubuntu-latest
    steps:
      - name: Creating AZ task
        env:
          AZURE_ORG: ${{ secrets.AZURE_ORG }}
          AZURE_PROJECT: ${{ secrets.AZURE_PROJECT }}
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
        run: |
          PAYLOAD=$(cat <<EOF
          [
            { "op": "add", "path": "/fields/System.Title", "value": "${{ github.event.inputs.title }}" },
            { "op": "add", "path": "/fields/System.Description", "value": "${{ github.event.inputs.description }}" },
            { "op": "add", "path": "/fields/System.AreaPath", "value": "${{ github.event.inputs.areaPath }}" }
          ]
          EOF
          )

          curl -X POST "https://dev.azure.com/$AZURE_ORG/$AZURE_PROJECT/_apis/wit/workitems/148800?api-version=7.1" \
            -H "Authorization: Basic $(echo -n :$AZURE_PAT | base64)"